[package]
name = "peernet-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
peernet-core = { path = "../peernet-core" }
peernet-proto = { path = "../peernet-proto" }
tokio = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }

[dev-dependencies]
peernet-client = { path = "../peernet-client" }
